version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms${ES_HEAP_SIZE:-1g} -Xmx${ES_HEAP_SIZE:-1g}"
      - xpack.security.enabled=${ES_SECURITY_ENABLED:-false}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-}
      - "thread_pool.write.queue_size=1000"
      - logger.org.elasticsearch.threadpool.ThreadPool=ERROR
      - logger.level=ERROR
    ports:
      - "${ES_PORT:-9200}:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./Utils:/app/Utils
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: ${ES_MEMORY_LIMIT:-1.5G}
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  dash:
    build:
      context: .
      dockerfile: dashboard/Dockerfile
    environment:
      - ES_HOST=elasticsearch:9200
      - ES_PASSWORD=${ELASTIC_PASSWORD:-}
    ports:
      - "${DASH_PORT:-8050}:8050"
    volumes:
      - ./dashboard:/app/dashboard
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./config/nginx/${ENV:-local}:/etc/nginx/conf.d
      - ./config/nginx/logs:/var/log/nginx
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - dash
      - elasticsearch
    networks:
      - default
    restart: unless-stopped

  francetravail:
    build:
      context: ./ETL/Extract/FranceTravail
      dockerfile: Dockerfile
    environment:
      - ES_HOST=${ES_HOST}
      - DATA_RAW_DIR=${DATA_RAW_DIR}
      - DATA_LOG_DIR=${DATA_LOG_DIR}
    volumes:
      - ./ETL:/app/ETL
      - ./data/raw/francetravail:/app/data/raw/francetravail
      - ./data/transformed/francetravail:/app/data/transformed/francetravail
      - ./data/processed/francetravail:/app/data/processed/francetravail
      - ./data/logs/francetravail:/app/data/logs/francetravail
      - ./Utils:/app/Utils
    networks:
      - default
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: unless-stopped

networks:
  default:
    name: jobmarket-network

volumes:
  es_data:
    name: jobmarket_elasticsearch_data
    external: true 