version: '3.8'

services:
  elasticsearch:
    ports:
      - "9200:9200"    # On expose elasticsearch uniquement en local
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - xpack.security.enabled=false

  dash:
    ports:
      - "8050:8050"    # On expose le dashboard uniquement en local

  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../config/nginx/local:/etc/nginx/conf.d
      - ../../config/nginx/ssl:/etc/nginx/ssl:ro
      - ../../config/nginx/logs:/var/log/nginx