version: '3.8'

services:
  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"    # Plus de mémoire en prod
      - xpack.security.enabled=true      # Sécurité activée en prod
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  dash:
    environment:
      - ES_PASSWORD=${ELASTIC_PASSWORD}  # Authentification en prod

  nginx:
    ports:
      - "80:80"
      - "443:443"                        # HTTPS en prod
    volumes:
      - ../nginx/prod:/etc/nginx/conf.d
      - ../nginx/logs:/var/log/nginx
      - /etc/letsencrypt/live/jobmarketv2.eastus.cloudapp.azure.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/jobmarketv2.eastus.cloudapp.azure.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro