# Utiliser l'image Selenium comme base
FROM selenium/standalone-chrome:latest

# Ajouter Python et pip
USER root
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    apt-get clean

# Définir le répertoire de travail
WORKDIR /app

# Copier vos fichiers
COPY . /app

# Installer Selenium via pip
RUN apt install -y python3-selenium

# Commande par défaut
CMD ["python", "main.py"]



